package:
  name: q2-skani
  version: {{ PLUGIN_VERSION }}
source:
  path: ..
build:
  script: make install
requirements:
  host:
  - python {{ python }}
  - setuptools
  - versioningit
  - wheel
  run:
  - pandas
  - qiime2 {{ qiime2 }}
  - q2-types {{ q2_types }}
  - skani
  build:
  - python {{ python }}
  - setuptools
  - versioningit
test:
  requires:
  - parameterized
  imports:
  - q2_skani
  - qiime2.plugins.skani
  commands:
  - pytest --pyargs q2_skani
about:
  home: https://github.com/bokulich-lab/q2-skani
  license: BSD-3-Clause
  license_family: BSD
