name: QIIME 2 CI
on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  qiime-ci:
    uses: qiime2/distributions/.github/workflows/lib-ci-dev.yaml@dev
    with:
      distro: tiny
      recipe-path: 'conda-recipe'
